### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by krthr** [BaseMax/FilterInputJs#1]
Hey! Great lib...

I have a question... what are you using to minify the .js? Why dont you use Webpack?

**Comment by krthr** [comment]
I could help adding the webpack config... And.. we could publish it on npm!

**Comment by BaseMax** [comment]
Hey @krthr,

Thank so much,
> what are you using to minify the .js?

A tool and service.
I did not remember this at now.
It's important?

> Why don't you use Webpack?

Do you want to create a website using Nodejs?
We can do it...
Do you help to do it?

Regards,
Max

**Comment by BaseMax** [comment]
> I could help adding the webpack config...

Thanks,

>  And.. we could publish it on npm!

Yeah, of course, I have an account there.

**Comment by krthr** [comment]
> It's important?

It would be nice to be able to install FilterInputJs via npm. Webpack will help build the file for production automatically.

**Comment by krthr** [comment]
#2

**Comment by BaseMax** [comment]
Hey @krthr,

Thank so much,

Wow, we have published this package...
https://www.npmjs.com/package/filterinput

Can you complete the Filters feature and TODO list?

Regards,
Max

**Comment by krthr** [comment]
> Hey @krthr,
> 
> Thank so much,
> 
> Wow, we have published this package...
> https://www.npmjs.com/package/filterinput
> 
> Can you complete the Filters feature and TODO list?
> 
> Regards,
> Max

Great!
I will see the TODO items and try to complete the filters

**Comment by BaseMax** [comment]
> Great!
> I will see the TODO items and try to complete the filters

Hi,

Thank you @krthr,

At first, please not work on the restrict allowed languages.
Because it requires deep knowledge from UTF-8.
https://github.com/BaseMax/FilterInputJs/issues/4

We can do it in the next step.

Regards,
Max

**Comment by BaseMax** [comment]
Hi,

How are you?
What's up? @krthr 

Regards,
Max

**Comment by BaseMax** [comment]
Hi,

How are you? @krthr

Regards,
Max

**Comment by krthr** [comment]
Hi! It was a busy week ;) I'm working in the `data-filter-lang` item.

**Comment by krthr** [comment]
I think we can access to the data attributes using the `dataset` property
 https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by BaseMax** [comment]
Hi,

How are you?
What's up? @krthr

Regards,
Max

**Comment by BaseMax** [comment]
Hi,

How are you?
What's up? @krthr

Regards,
Max

**Comment by BaseMax** [comment]
Hi,

How are you?
What's up? @krthr

Regards,
Max
